server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 'root'
        platform: mysql
        url: jdbc:mysql://localhost/desafio?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: validate
        show-sql: true
    profiles: 
        active: google

authserver:
  hostname: http://localhost:9092
security:  
  oauth2:
    client:
      clientId: 978997156419-402b02sq1b06mjomjdogkoo7pmqj9h7l.apps.googleusercontent.com 
      clientSecret: 74VGRlahRAgLC-DunLgX3kIL
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
